name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libffi-dev libssl-dev cmake build-essential python3-dev
        python -m pip install --upgrade pip
        pip install buildozer cython kivy

    - name: Build APK with buildozer
      run: |
        # Let buildozer handle everything automatically
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-apk
        path: bin/*.apk
