name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          git zip unzip openjdk-8-jdk wget \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev \
          build-essential ccache m4 libtool \
          libltdl-dev libffi-dev libssl-dev python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install buildozer==1.4.0
        pip install cython==0.29.33
        pip install kivy==2.1.0

    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build with buildozer
      run: |
        # Accept all licenses
        export BUILDOZER_LOG_LEVEL=2
        export ANDROID_ACCEPT_SDK_LICENSE=1

        # Build the APK
        yes | buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
