name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache Buildozer directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
    
    - name: Create missing directories
      run: |
        mkdir -p app/core app/ui app/data assets/icons data
        touch app/__init__.py app/core/__init__.py app/ui/__init__.py app/data/__init__.py
    
    - name: Initialize buildozer if needed
      run: |
        if [ ! -f buildozer.spec ]; then
          cp buildozer-minimal.spec buildozer.spec
        fi
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: accounting-app-debug
        path: bin/*.apk
        retention-days: 30
    
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: .buildozer/android/platform/build-*/logs/
        retention-days: 7
